#!/bin/sh

spotify="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player."

[ -z $ALSA_DEVICE_ID ] && ALSA_DEVICE_ID=0

case "$1" in
	"on") cmus-remote -Q || cmus ;;
	"off") killall cmus ;;
	"up") amixer -q -c $ALSA_DEVICE_ID -- sset Master playback 2dB+ ;;
	"down") amixer -q -c $ALSA_DEVICE_ID -- sset Master playback 2dB- ;;
	"mute") amixer -D pulse set Master 1+ toggle ;;
	"pause") cmus-remote --pause ;;
	"pause_playback") cmus-remote --pause-playback ;;
	"mpv_pause") echo '{ "command": ["cycle", "pause"] }' | socat - ~/temp/mpv-socket >> /dev/null ;;
	"forward") cmus-remote --seek +5 ;;
	"back") cmus-remote --seek -5 ;;
	"mpv_forward") echo '{ "command": ["seek", 5, "relative"] }' | socat - ~/temp/mpv-socket >> /dev/null ;;
	"mpv_back") echo '{ "command": ["seek", -5, "relative"] }' | socat - ~/temp/mpv-socket >> /dev/null ;;
	"mpv_faster") echo '{ "command": ["add", "speed", 0.05] }' | socat - ~/temp/mpv-socket >> /dev/null ;;
	"mpv_slower") echo '{ "command": ["add", "speed", -0.05] }' | socat - ~/temp/mpv-socket >> /dev/null ;;
	"next") cmus-remote --next ;;
	"prev") cmus-remote --prev ;;
	"replay") cmus-remote -k 00:00:00 ;;
	"spotify_play") $spotify"PlayPause" >/dev/null ;;
	"spotify_next") $spotify"Next" >/dev/null ;;
	"spotify_prev") $spotify"Previous" >/dev/null ;;
esac
