#!/bin/sh

# Converts a notebook with entries delineated by
# %Y-%m-%d %H:%M <title>
# to a markdown format of headers with self-referenced anchors

echo "\
---\n\
Title: Notebook\n\
Modified: `date '+%Y-%m-%d'`\n\
Status: Published\n\
...\n"

sed -E 's/'\
'^([0-9]{4})-([0-9]{2})-([0-9]{2})\s'\
'[0-9]{2}:[0-9]{2}\s(.*)/'\
'#### <a name="\1\2\3" href="#\1\2\3">\1-\2-\3<\/a> \4/'
