#!/bin/bash

if (($# != 1)) || [[ $1 = *[![:digit:]]* ]]; then
    echo "Usage: countdown seconds"
    exit
fi;

t=$1 remaining=$1
SECONDS=0

tput civis # hide cursor
while sleep .2; do
    printf '\r%3d\r' "$remaining"
    if (( (remaining=t-SECONDS) <= 0 )); then
        break
    fi
done
tput cnorm # show cursor

