#!/bin/sh

# Opens the STDIN content in an editable temporary buffer in $EDITOR

[ -z $TMPDIR ] && TMPDIR="/tmp"
tmpfile=$(mktemp $TMPDIR/st-edit.XXXXXX)
cat > "$tmpfile"

if [ "$DISPLAY" ]; then
    st -e $EDITOR $tmpfile && rm $tmpfile
else
    tmux new-window "$EDITOR $tmpfile; rm $tmpfile"
fi
