#!/bin/sh

# Display the links visible in STDIN in a menu, then either open with $1 or copy to clipboard
regex='(((http|https|ftp|gopher)|mailto)[.:][^ >"\t]*|www\.[-a-z0-9.]+)[^ .,;\t>">\):]'
[ "$DISPLAY" ] && menuapp="dmenu" || menuapp="slmenu"
url=$(grep -Po "$regex" | $menuapp -l 5 -p "Go:") || exit
app="$1"
if [ -z $app ]; then
    if [ "$DISPLAY" ] ; then
        echo $url | xsel -b
    else
        tmux set-buffer "$url"
    fi
else
	$app "$url"
fi
