#!/bin/sh

# Displays the links visible in STDIN in dmenu to open in $BROWSER
regex='(((http|https|ftp|gopher)|mailto)[.:][^ >"\t]*|www\.[-a-z0-9.]+)[^ .,;\t>">\):]'
url=$(grep -Po "$regex" | dmenu -l 5 -p "Go:") || exit
$BROWSER "$url"
