#!/bin/bash

DEFAULT_DOCUMENT="index.html"
rm -f out
mkfifo out
trap "rm -f out" EXIT
while true ; do
    cat out | nc -l -p 8001 > >( # parse the netcat output, to build the answer redirected to the pipe "out".
    export REQUEST_METHOD=
    export CONTENT_LENGTH=
    export CONTENT_TYPE=
    export QUERY_STRING_POST=
    while read -r line; do
        line=$(echo "$line" | tr -d '\r\n')
        echo $line
        #if echo "$line" | grep -qE '^GET /'  # if line starts with "GET /"
        if [[ "$line" =~ ^(GET|POST) ]] ; then
            REQUEST_METHOD=$(cut -d ' ' -f1 <<< "$line")
            REQUEST=$(cut -d ' ' -f2 <<< "$line") # extract the request
            QUERY_STRING=$(cut -d '?' -f2 <<< "$REQUEST")
            if [[ -n "$QUERY_STRING" ]]; then
                REQUEST=$(cut -d '?' -f1 <<< "$REQUEST")
            fi
            echo Request: $REQUEST
        elif [ -z "$line" ] # empty line / end of request
        then
            if [[ "$REQUEST_METHOD" == "POST" ]]; then
                read -r QUERY_STRING_POST
                echo $QUERY_STRING_POST
            fi
            [[ -n "$QUERY_STRING" ]] && echo "$QUERY_STRING"
            # call a script here
            # Note: REQUEST is exported, so the script can parse it (to answer 200/403/404 status code + content)
            if [[ "$REQUEST" == "/" ]]; then
                REQUEST="$DEFAULT_DOCUMENT"
            elif [[ "$REQUEST" =~ cgi$ ]]; then
                echo -e "\nCGI Response:\n"
                ./"$REQUEST" | tee out
                continue
            fi
            echo -e "HTTP/1.1 200 OK\nContent-type: text/html\n\n$(cat ./$REQUEST)" > out
        elif [[ "$REQUEST_METHOD" == "POST" ]]; then
            # Collect the POST header fields and values to pass to CGI script
            hdr_field=$(echo "$line" | cut -d ' ' -f1 | tr -d ':')
            value=$(echo "$line" | cut -d ' ' -f2)
            case "$hdr_field" in
                Content-Length) 
                    #echo setting CONTENT_LENGTH to $value
                    CONTENT_LENGTH=$value
                    ;;
                Content-Type)
                    #echo setting CONTENT_TYPE to $value
                    CONTENT_TYPE=$value
                    ;;
            esac
        fi
    done
    )
done
