#!/usr/bin/perl

use strict;
use warnings;

( $ARGV[1] ) or die "Must specify input file and base variable\n";

my $infile = $ARGV[0];
my $output = "\@$ARGV[1]\@\n";
my $input;

open(INFILE, "< $infile") or die "Couldn't open $infile: $!\n";
{
    local $/; # enable "slurp" mode
    $input = <INFILE>; 
}
close(INFILE);

while ($output =~ /\@\w+\@/) {
    my $varname = $&;
    ($input =~ /\#$varname\n(.*?)\n\n/s) or die "Did not find variable $varname in $infile.\n";
    my @varblock = split (/\n/, $1);
    my $randline = $varblock[rand @varblock];
    $randline =~ s/(.*)\s*\#.*/$1/; # Strip trailing (pound-sign) comments
    $output =~ s/$varname/$randline/;
}
print $output;
