#!/bin/bash

# For *most* ops, 'rsync -auvC' provides the satisfactory behavior

[ ! $2 ] && echo "Need to specify a source and destination" && exit

set -x
#rsync -avChum 
rsync --archive --verbose --cvs-exclude \
    --ignore-missing-args --human-readable --update \
    --prune-empty-dirs --progress --exclude='*.sw*p'  \
    "$@"
set +x

# For backups, use something similar to this:
# rsync --archive --one-file-system --hard-links \
#  --human-readable --inplace --numeric-ids --delete \
#    --delete-excluded --exclude-from=excludes.txt \
#      --link-dest=/backup/rsync/asylum/_home_asylum.2005-07-25.15-32-42 \
#        asylum:/home/asylum/ /backup/rsync/asylum/_home_asylum.incomplete/
