#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
#ps1="(.*)\s[~/].*\\$\s" # The regex representing the ps1 command line prompt
ps1=".*[~/].*\\$\s" # The regex representing the ps1 command line prompt
chosen="$(grep "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -i -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
awk "/^$chosen$/{p=1;print;next} p&&/^$ps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
