#!/bin/perl -w

# Parse html document, extract the table only, convert to CSV
# Assume first row to be the header row
# Wrap each field in double quotes 

local $/; # Enable slurp mode to read the whole STDIN
$_ = <STDIN>;

s/.*(<table.*<\/table>).*/$+/is; # strip out just the table
s/<!--.*-->//gs; # Strip comments
s/\n//g;
s/>\s+</></g; # Strip extraneous spacing
s/<\/(TR|THEAD|TBODY)[^>]*>/\n/ig; # Correspond newlines with CSV rows
s/<\/?(TABLE|TR|THEAD|TBODY)[^>]*>//ig; # Remove unnecessary tags
s/"/'/g; # Inner element double quotes to single, not to conflict with CSV
# Surround all elements with double quotes
s/^<T[DH][^>]*>|<\/?T[DH][^>]*>$/"/igm;
s/\s*<\/T[DH][^>]*><T[DH][^>]*>/","/igm;
s/^\s*\n//m; # Remove any remaining blank lines

print "$_\n";
