#!/bin/sh

# Strips out just the table from the html document
# Removes any html inner comments
# Converts to CSV, assuming first row to be header row
# Wraps each field in double quotes 
# Removes double quotes in header line (in the sed '1 s/"//g' statement)
# Removes any formatting markup from header line

sed -re "/<table/,/<\/table/!d" \
    -e "s/.*(<table)/\1/; s/(<\/table>).*/\1/;" \
    -e 's/<!--.*-->//g; s/^[[:space:]]*//g; s/[[:space:]]*$//g' |\
tr -d '\n' |\
sed -re 's/<\/(TR|THEAD|TBODY)[^>]*>/\n/Ig' \
    -e 's/<\/?(TABLE|TR|THEAD|TBODY)[^>]*>//Ig' \
    -e "s/\"/'/g" |\
sed -re 's/^<T[DH][^>]*>|<\/?T[DH][^>]*>$/"/Ig' \
    -e 's/[[:space:]]*<\/T[DH][^>]*><T[DH][^>]*>/","/Ig' \
    -e '/^[[:space:]]*$/d' \
    -e '1s/"//g; 1s/<\/?[^>]*>//g'
